### ISSUE TITLE
Error in file-generator

### ISSUE THREAD

**Issue by majsathish** [mminella/mainframeingestion#2]
As per the recommendation  , I tried buidling the File -generator , getting the following error [ERROR] Failed to execute goal on project file-generator: Could not resolve dependencies for project io.spring.batch:file-generator:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: net.sf:jrecord:jar:0.90, net.sf:cb2xml:jar:0.90: Could not find artifact net.sf:jrecord:jar:0.90 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mminella** [comment]
Ah.  Yes.  JRecord and cb2xml are not in a Maven repository.  You'll need to download the jars and install them locally.  The commands I used to do the install are:
```
mvn install:install-file -Dfile=cb2xml.jar -DgroupId=net.sf -DartifactId=cb2xml -Dversion=0.90 -Dpackaging=jar
mvn install:install-file -Dfile=JRecord.jar -DgroupId=net.sf -DartifactId=JRecord -Dversion=0.90 -Dpackaging=jar
```

**Comment by majsathish** [comment]
Thanks for the quick turnaround.
Where did you download the jars from ?

**Comment by mminella** [comment]
I just pushed them into a the `bin/libs` folder of this project.
