### ISSUE TITLE
Mainframe Batch File Processing Migration with  Spring batch clarification 

### ISSUE THREAD

**Issue by majsathish** [mminella/mainframeingestion#3]
In the demo you are using .dat file and explained that is a binary and reading your content with copybooy
                                                                         
        03  DTAR1000-REC.                                                
            10 DTAR1000-STORE-NO       PIC S9(4) COMP.
            10 DTAR1000-REGION-NO      PIC S9(4) COMP.
            10 DTAR1000-STORE-NAME     PIC X(50).                        
            10 DTAR1000-NEW-STORE      PIC X(1).                         
            10 DTAR1000-ACTIVE-STORE   PIC X(1).                         
            10 DTAR1000-CLOSED-STORE   PIC X(1).                         
            10 DTAR1000-DC-TYPE        PIC X(1).                         
            10 DTAR1000-SRC-TYPE       PIC X(1). 
            10 DTAR1000-HO-TYPE        PIC X(1). 

I have a similar situation where I should read a character FB Dataset of mainframe using PL1 program using DCL Gen , we are migrating the batch which  the PL1 process the character file data set with DCLGEN copybook to Java Based Batch application  . We are planning to migrate this using spring batch and spring task flow. Can you give your recommendation on whether our business case can we reuse the implementation which your team have released?
 
[PL1_Data_DCLGen Layout.docx](https://github.com/mminella/mainframeingestion/files/2470583/PL1_Data_DCLGen.Layout.docx)

**Comment by mminella** [comment]
I don't see why not.  Although assuming you're using a JDBC driver, you probably wouldn't even need the JRecord piece.
